Vagrant.configure("2") do |config|
  
  # # Configuration de la première machine virtuelle
  # config.vm.define "node1.tp2.cloud" do |firstmachine|
  #   firstmachine.vm.box = "generic/rocky9"
  #   firstmachine.vm.hostname = "node1.tp2.cloud"
  #   firstmachine.vm.network "private_network", ip: "10.1.1.11"
  #   firstmachine.vm.provider "virtualbox" do |vb|
  #     vb.gui = true 
  #     vb.name = "node1.tp2.cloud"
  #     vb.memory = "1024"
  #   end
  #   firstmachine.vm.provision "shell", path: "setup.sh"
  # end

  # # Configuration de la deuxième machine virtuelle
  # config.vm.define "node2.tp2.cloud" do |secondmachine|
  #   secondmachine.vm.box = "generic/rocky9"
  #   secondmachine.vm.hostname = "node2.tp2.cloud"
  #   secondmachine.vm.network "private_network", ip: "10.1.1.12"
  #   secondmachine.vm.provider "virtualbox" do |vb|
  #     vb.gui = true
  #     vb.name = "node2.tp2.cloud"
  #     vb.memory = "1024"
  #   end
  #   secondmachine.vm.provision "shell", path: "setup.sh"
  # end

  # Configuration de la troisième machine virtuelle
  config.vm.define "node3.tp2.cloud" do |thirdmachine|
    thirdmachine.vm.box = "generic/rocky9"
    thirdmachine.vm.hostname = "node3.tp2.cloud"
    thirdmachine.vm.network "private_network", ip: "10.1.1.13"
    thirdmachine.vm.provider "virtualbox" do |vb|
      vb.gui = true 
      vb.name = "node3.tp2.cloud"
      vb.memory = "1024"
    end
    thirdmachine.vm.provision "shell", path: "setup.sh"
  end

  # Configuration de la quatrième machine virtuelle
  config.vm.define "node4.tp2.cloud" do |fourthmachine|
    fourthmachine.vm.box = "generic/rocky9"
    fourthmachine.vm.hostname = "node4.tp2.cloud"
    fourthmachine.vm.network "private_network", ip: "10.1.1.14"
    fourthmachine.vm.provider "virtualbox" do |vb|
       vb.gui = true 
       vb.name = "node4.tp2.cloud"
       vb.memory = "1024"
    end
    fourthmachine.vm.provision "shell", path: "setup.sh"
  end

end
