# Créer un nouveau répertoire de travail
$ mkdir vagrant
$ cd vagrant

# Initialiser un nouveau Vagrantfile
$ vagrant init rocky9-cloud

# Editer le Vagrantfile pour qu'il ressemble à :
$ cat Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "rocky9-cloud"
  # On désactive la synchro automatique du dossier courant, pour que ça marche, il faut les Guest Additions
  config.vm.synced_folder '.', '/vagrant', disabled: true

  # Ajout de la conf cloud-init
  config.vm.cloud_init do |cloud_init|
    cloud_init.content_type = "text/cloud-config"
    cloud_init.path = 'user-data'
  end
end
